name: Deploy VuePress site

on:
  push:
    branches: [main]   # 监听 main 分支推送

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Enable corepack & install deps
        run: |
          corepack enable
          pnpm install --no-frozen-lockfile

      - name: Build VuePress
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/.vuepress/dist
